"""current baseline schema

Revision ID: 47c41e5114e8
Revises: 
Create Date: 2025-12-16 22:01:28.425913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47c41e5114e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_name', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('rerank', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('worksheet_number', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.String(length=24), nullable=True),
    sa.Column('scanned_commit_sha', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_results_user_workspace_id', 'analysis_results', ['user_id', 'workspace_id'], unique=False)
    op.create_index('idx_analysis_results_user_workspace_worksheet', 'analysis_results', ['user_id', 'workspace_id', 'worksheet_number'], unique=False)
    op.create_index('idx_analysis_results_workspace_id', 'analysis_results', ['workspace_id'], unique=False)
    op.create_index('ix_analysis_results_repo_user', 'analysis_results', ['repository_name', 'user_id'], unique=False)
    op.create_index('ix_analysis_results_user_id', 'analysis_results', ['user_id'], unique=False)
    op.create_index('ix_analysis_results_user_worksheet', 'analysis_results', ['user_id', 'worksheet_number'], unique=False)
    op.create_table('azure_devops_analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_name', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('rerank', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('worksheet_number', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.String(length=24), nullable=True),
    sa.Column('scanned_commit_sha', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_azure_org_project_repo', 'azure_devops_analysis_results', ['organization_name', 'project_name', 'repository_name'], unique=False)
    op.create_index('idx_azure_scanned_commit_sha', 'azure_devops_analysis_results', ['scanned_commit_sha'], unique=False)
    op.create_index('idx_azure_user_org', 'azure_devops_analysis_results', ['user_id', 'organization_name'], unique=False)
    op.create_index('idx_azure_user_org_worksheet', 'azure_devops_analysis_results', ['user_id', 'organization_name', 'worksheet_number'], unique=False)
    op.create_index('idx_azure_user_project_worksheet', 'azure_devops_analysis_results', ['user_id', 'project_name', 'worksheet_number'], unique=False)
    op.create_index('idx_azure_user_worksheet', 'azure_devops_analysis_results', ['user_id', 'worksheet_number'], unique=False)
    op.create_index('idx_azure_user_workspace_id', 'azure_devops_analysis_results', ['user_id', 'workspace_id'], unique=False)
    op.create_index('idx_azure_user_workspace_worksheet', 'azure_devops_analysis_results', ['user_id', 'workspace_id', 'worksheet_number'], unique=False)
    op.create_index('idx_azure_workspace_id', 'azure_devops_analysis_results', ['workspace_id'], unique=False)
    op.create_table('cloud_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('cloud_provider', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('cloudname', sa.String(length=255), nullable=True),
    sa.Column('worksheet_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rerank', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cloud_scans_provider', 'cloud_scans', ['cloud_provider'], unique=False)
    op.create_index('idx_cloud_scans_status', 'cloud_scans', ['status'], unique=False)
    op.create_index('idx_cloud_scans_user_cloudname', 'cloud_scans', ['user_id', 'cloudname'], unique=False)
    op.create_index('idx_cloud_scans_user_cloudname_worksheet', 'cloud_scans', ['user_id', 'cloudname', 'worksheet_number'], unique=False)
    op.create_index('idx_cloud_scans_user_id', 'cloud_scans', ['user_id'], unique=False)
    op.create_index('idx_cloud_scans_user_worksheet', 'cloud_scans', ['user_id', 'worksheet_number'], unique=False)
    op.create_table('fix_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.String(length=24), nullable=True),
    sa.Column('repo_type', sa.String(length=50), nullable=False),
    sa.Column('repo_identifier', sa.String(length=512), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('finding_id', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('cwe_id', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('pr_url', sa.String(length=500), nullable=True),
    sa.Column('pr_number', sa.String(length=50), nullable=True),
    sa.Column('pr_title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('fix_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pr_created_at', sa.DateTime(), nullable=True),
    sa.Column('pr_merged_at', sa.DateTime(), nullable=True),
    sa.Column('pr_closed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fix_request_finding', 'fix_requests', ['finding_id', 'file_path', 'line_start'], unique=False)
    op.create_index('idx_fix_request_pr_number', 'fix_requests', ['repo_identifier', 'pr_number'], unique=False)
    op.create_index('idx_fix_request_repo', 'fix_requests', ['repo_type', 'repo_identifier'], unique=False)
    op.create_index('idx_fix_request_status', 'fix_requests', ['status'], unique=False)
    op.create_index('idx_fix_request_user_id', 'fix_requests', ['user_id'], unique=False)
    op.create_index('idx_fix_request_user_workspace', 'fix_requests', ['user_id', 'workspace_id'], unique=False)
    op.create_index('idx_fix_request_workspace', 'fix_requests', ['workspace_id'], unique=False)
    op.create_table('github_analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_name', sa.String(length=255), nullable=False),
    sa.Column('repository_owner', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('rerank', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('worksheet_number', sa.Integer(), nullable=False),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_github_owner_repo', 'github_analysis_results', ['repository_owner', 'repository_name'], unique=False)
    op.create_index('idx_github_repo_user', 'github_analysis_results', ['repository_name', 'user_id'], unique=False)
    op.create_index('idx_github_status', 'github_analysis_results', ['status'], unique=False)
    op.create_index('idx_github_user_owner', 'github_analysis_results', ['user_id', 'repository_owner'], unique=False)
    op.create_index('idx_github_user_owner_worksheet', 'github_analysis_results', ['user_id', 'repository_owner', 'worksheet_number'], unique=False)
    op.create_index('idx_github_user_worksheet', 'github_analysis_results', ['user_id', 'worksheet_number'], unique=False)
    op.create_table('gitlab_scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_name', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('project_path', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('rerank', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workspace', sa.String(length=24), nullable=True),
    sa.Column('gitlab_instance_url', sa.String(length=500), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('scanned_commit_sha', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gitlab_scan_project_id', 'gitlab_scan_results', ['project_id'], unique=False)
    op.create_index('idx_gitlab_scan_project_path', 'gitlab_scan_results', ['project_path'], unique=False)
    op.create_index('idx_gitlab_scan_repo_user', 'gitlab_scan_results', ['repository_name', 'user_id'], unique=False)
    op.create_index('idx_gitlab_scan_status', 'gitlab_scan_results', ['status'], unique=False)
    op.create_index('idx_gitlab_scan_user_project', 'gitlab_scan_results', ['user_id', 'project_id'], unique=False)
    op.create_index('idx_gitlab_scan_user_project_workspace', 'gitlab_scan_results', ['user_id', 'project_id', 'workspace'], unique=False)
    op.create_index('idx_gitlab_scan_user_workspace', 'gitlab_scan_results', ['user_id', 'workspace'], unique=False)
    op.create_table('ignored_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('ignore_type', sa.String(length=20), nullable=False),
    sa.Column('finding_id', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('cwe_id', sa.String(length=20), nullable=True),
    sa.Column('workspace_id', sa.String(length=24), nullable=True),
    sa.Column('repo_type', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ignored_at', sa.DateTime(), nullable=True),
    sa.Column('ignored_by', sa.String(length=255), nullable=True),
    sa.Column('worksheet_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cwe_lookup', 'ignored_findings', ['user_id', 'repo_name', 'ignore_type', 'cwe_id', 'file_path'], unique=False)
    op.create_index('idx_ignore_lookup', 'ignored_findings', ['user_id', 'repo_name', 'ignore_type', 'finding_id', 'file_path'], unique=False)
    op.create_index('idx_ignore_user_repo_worksheet', 'ignored_findings', ['user_id', 'repo_name', 'worksheet_number'], unique=False)
    op.create_index('idx_ignore_user_worksheet', 'ignored_findings', ['user_id', 'worksheet_number'], unique=False)
    op.create_index('idx_user_repo', 'ignored_findings', ['user_id', 'repo_name'], unique=False)
    op.create_table('repository_scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.String(length=24), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('repo_type', sa.String(length=50), nullable=False),
    sa.Column('repo_identifier', sa.String(length=512), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rerank', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_repo_status', 'repository_scan_results', ['status'], unique=False)
    op.create_index('idx_repo_timestamp', 'repository_scan_results', ['timestamp'], unique=False)
    op.create_index('idx_repo_type_identifier', 'repository_scan_results', ['repo_type', 'repo_identifier'], unique=False)
    op.create_index('idx_repo_user_type', 'repository_scan_results', ['user_id', 'repo_type'], unique=False)
    op.create_index('idx_repo_user_workspace', 'repository_scan_results', ['user_id', 'workspace_id'], unique=False)
    op.create_index('idx_repo_workspace_id', 'repository_scan_results', ['workspace_id'], unique=False)
    op.create_table('zap_scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('scan_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.String(length=24), nullable=True),
    sa.Column('worksheet_number', sa.Integer(), nullable=False),
    sa.Column('rerank', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('scan_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=True),
    sa.Column('severity_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('zap_version', sa.String(length=50), nullable=True),
    sa.Column('zap_exit_code', sa.Integer(), nullable=True),
    sa.Column('report_path', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_zap_scan_scan_type', 'zap_scan_results', ['scan_type'], unique=False)
    op.create_index('idx_zap_scan_status', 'zap_scan_results', ['status'], unique=False)
    op.create_index('idx_zap_scan_target_url', 'zap_scan_results', ['target_url'], unique=False)
    op.create_index('idx_zap_scan_timestamp', 'zap_scan_results', ['timestamp'], unique=False)
    op.create_index('idx_zap_scan_user_id', 'zap_scan_results', ['user_id'], unique=False)
    op.create_index('idx_zap_scan_user_worksheet', 'zap_scan_results', ['user_id', 'worksheet_number'], unique=False)
    op.create_index('idx_zap_scan_user_workspace', 'zap_scan_results', ['user_id', 'workspace_id'], unique=False)
    op.create_index('idx_zap_scan_user_workspace_worksheet', 'zap_scan_results', ['user_id', 'workspace_id', 'worksheet_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_zap_scan_user_workspace_worksheet', table_name='zap_scan_results')
    op.drop_index('idx_zap_scan_user_workspace', table_name='zap_scan_results')
    op.drop_index('idx_zap_scan_user_worksheet', table_name='zap_scan_results')
    op.drop_index('idx_zap_scan_user_id', table_name='zap_scan_results')
    op.drop_index('idx_zap_scan_timestamp', table_name='zap_scan_results')
    op.drop_index('idx_zap_scan_target_url', table_name='zap_scan_results')
    op.drop_index('idx_zap_scan_status', table_name='zap_scan_results')
    op.drop_index('idx_zap_scan_scan_type', table_name='zap_scan_results')
    op.drop_table('zap_scan_results')
    op.drop_index('idx_repo_workspace_id', table_name='repository_scan_results')
    op.drop_index('idx_repo_user_workspace', table_name='repository_scan_results')
    op.drop_index('idx_repo_user_type', table_name='repository_scan_results')
    op.drop_index('idx_repo_type_identifier', table_name='repository_scan_results')
    op.drop_index('idx_repo_timestamp', table_name='repository_scan_results')
    op.drop_index('idx_repo_status', table_name='repository_scan_results')
    op.drop_table('repository_scan_results')
    op.drop_index('idx_user_repo', table_name='ignored_findings')
    op.drop_index('idx_ignore_user_worksheet', table_name='ignored_findings')
    op.drop_index('idx_ignore_user_repo_worksheet', table_name='ignored_findings')
    op.drop_index('idx_ignore_lookup', table_name='ignored_findings')
    op.drop_index('idx_cwe_lookup', table_name='ignored_findings')
    op.drop_table('ignored_findings')
    op.drop_index('idx_gitlab_scan_user_workspace', table_name='gitlab_scan_results')
    op.drop_index('idx_gitlab_scan_user_project_workspace', table_name='gitlab_scan_results')
    op.drop_index('idx_gitlab_scan_user_project', table_name='gitlab_scan_results')
    op.drop_index('idx_gitlab_scan_status', table_name='gitlab_scan_results')
    op.drop_index('idx_gitlab_scan_repo_user', table_name='gitlab_scan_results')
    op.drop_index('idx_gitlab_scan_project_path', table_name='gitlab_scan_results')
    op.drop_index('idx_gitlab_scan_project_id', table_name='gitlab_scan_results')
    op.drop_table('gitlab_scan_results')
    op.drop_index('idx_github_user_worksheet', table_name='github_analysis_results')
    op.drop_index('idx_github_user_owner_worksheet', table_name='github_analysis_results')
    op.drop_index('idx_github_user_owner', table_name='github_analysis_results')
    op.drop_index('idx_github_status', table_name='github_analysis_results')
    op.drop_index('idx_github_repo_user', table_name='github_analysis_results')
    op.drop_index('idx_github_owner_repo', table_name='github_analysis_results')
    op.drop_table('github_analysis_results')
    op.drop_index('idx_fix_request_workspace', table_name='fix_requests')
    op.drop_index('idx_fix_request_user_workspace', table_name='fix_requests')
    op.drop_index('idx_fix_request_user_id', table_name='fix_requests')
    op.drop_index('idx_fix_request_status', table_name='fix_requests')
    op.drop_index('idx_fix_request_repo', table_name='fix_requests')
    op.drop_index('idx_fix_request_pr_number', table_name='fix_requests')
    op.drop_index('idx_fix_request_finding', table_name='fix_requests')
    op.drop_table('fix_requests')
    op.drop_index('idx_cloud_scans_user_worksheet', table_name='cloud_scans')
    op.drop_index('idx_cloud_scans_user_id', table_name='cloud_scans')
    op.drop_index('idx_cloud_scans_user_cloudname_worksheet', table_name='cloud_scans')
    op.drop_index('idx_cloud_scans_user_cloudname', table_name='cloud_scans')
    op.drop_index('idx_cloud_scans_status', table_name='cloud_scans')
    op.drop_index('idx_cloud_scans_provider', table_name='cloud_scans')
    op.drop_table('cloud_scans')
    op.drop_index('idx_azure_workspace_id', table_name='azure_devops_analysis_results')
    op.drop_index('idx_azure_user_workspace_worksheet', table_name='azure_devops_analysis_results')
    op.drop_index('idx_azure_user_workspace_id', table_name='azure_devops_analysis_results')
    op.drop_index('idx_azure_user_worksheet', table_name='azure_devops_analysis_results')
    op.drop_index('idx_azure_user_project_worksheet', table_name='azure_devops_analysis_results')
    op.drop_index('idx_azure_user_org_worksheet', table_name='azure_devops_analysis_results')
    op.drop_index('idx_azure_user_org', table_name='azure_devops_analysis_results')
    op.drop_index('idx_azure_scanned_commit_sha', table_name='azure_devops_analysis_results')
    op.drop_index('idx_azure_org_project_repo', table_name='azure_devops_analysis_results')
    op.drop_table('azure_devops_analysis_results')
    op.drop_index('ix_analysis_results_user_worksheet', table_name='analysis_results')
    op.drop_index('ix_analysis_results_user_id', table_name='analysis_results')
    op.drop_index('ix_analysis_results_repo_user', table_name='analysis_results')
    op.drop_index('idx_analysis_results_workspace_id', table_name='analysis_results')
    op.drop_index('idx_analysis_results_user_workspace_worksheet', table_name='analysis_results')
    op.drop_index('idx_analysis_results_user_workspace_id', table_name='analysis_results')
    op.drop_table('analysis_results')
    # ### end Alembic commands ###
