"""add unified table for scans

Revision ID: 6a406f3fdfd1
Revises: 47c41e5114e8
Create Date: 2026-01-11 15:26:59.161200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a406f3fdfd1'
down_revision: Union[str, None] = '47c41e5114e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.String(length=24), nullable=True),
    sa.Column('repo_type', sa.String(length=50), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('hosted_git_url', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rerank', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scanned_commit_sha', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unified_org_project_repo', 'repo_scan_results', ['org_name', 'project_name', 'repo_name'], unique=False)
    op.create_index('idx_unified_repo_type_org_repo', 'repo_scan_results', ['repo_type', 'org_name', 'repo_name'], unique=False)
    op.create_index('idx_unified_status', 'repo_scan_results', ['status'], unique=False)
    op.create_index('idx_unified_timestamp', 'repo_scan_results', ['timestamp'], unique=False)
    op.create_index('idx_unified_user_repo_type', 'repo_scan_results', ['user_id', 'repo_type'], unique=False)
    op.create_index('idx_unified_user_workspace', 'repo_scan_results', ['user_id', 'workspace_id'], unique=False)
    op.create_index('idx_unified_workspace_id', 'repo_scan_results', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unified_workspace_id', table_name='repo_scan_results')
    op.drop_index('idx_unified_user_workspace', table_name='repo_scan_results')
    op.drop_index('idx_unified_user_repo_type', table_name='repo_scan_results')
    op.drop_index('idx_unified_timestamp', table_name='repo_scan_results')
    op.drop_index('idx_unified_status', table_name='repo_scan_results')
    op.drop_index('idx_unified_repo_type_org_repo', table_name='repo_scan_results')
    op.drop_index('idx_unified_org_project_repo', table_name='repo_scan_results')
    op.drop_table('repo_scan_results')
    # ### end Alembic commands ###
